### PR TITLE
feat(config): Config file can now be used for secret/password

### PR DESCRIPTION
**Pull request by joshuef**

### CODE REVIEW

**Comment by joshuef** [comment]
I don't know if it's an issue TBH.
Security is a sliding scale. This is better than command line flags... The convenience here is almost the same.

I think this has already been requested a few times.

Maybe we should just fire warnings? to establish that this is not necessarily the most secure method.

**Comment by joshuef** [comment]
@bochaco in the end, what more changes should be made here? Simply adding a warning upon use? Anything else to add for this to be acceptable? (@hunterlester thoughts?)

**Comment by bochaco** [comment]
yeah, we could warn them upon use and/or in the `--help` message, I guess the main concern to share with users is that their are stored unencrypted

**Comment by bochaco** [comment]
@joshuef , it'll be good to also remove these warnings:
```
warning: unused import: `std::fs`
  --> tests\cli_integration.rs:13:5
   |
13 | use std::fs;
   |     ^^^^^^^
   |
   = note: #[warn(unused_imports)] on by default
warning: unused `#[macro_use]` import
  --> tests\cli_integration.rs:16:1
   |
16 | #[macro_use]
   | ^^^^^^^^^^^^
```

**Comment by wardbr** [comment]
Hello,
Maybe I've missed it (only looked at this pull request): but if not there, you could add the requirement that the config file can only by read or written to by the owner and not anyone else. See https://wiki.archlinux.org/index.php/SSH_keys as example.

**Comment by joshuef** [comment]
thanks @wardbr . We've been assessing options along these lines. We definitely want to offer a secure alternative.

Right now I'm proposing this as more of a convenient stop-gap solution that'd let folks get back to using the CLI programmatically, without requiring human input. 

A plaintext config file is one simple solution there. As are env vars. But aye, the ideal would be not needing this and having a more complete/robust solution.

I think @bochaco has some ideas similar to your above suggestion waiting in the wings...

**Comment by joshuef** [comment]
I'm closing this PR in favor of #28 , which builds atop it (and will address your points @bochaco )

**Comment by wardbr** [comment]
Ok,
To be clear, what I proposed is what you have (=plaintext config file) + a check of no more rights than 'rwx --- ---'. But indeed not that important to have atm the most secure solution for non-interactive, batch mode e.g. for usage in IOT solutions. As long as it is clear what is should be eventually.

**Comment by joshuef** [comment]
Ah sorry, I'd not followed you there. Thanks for clarifying. Definitely an interesting option.

**Pull request closed without merging**
